# Authors and Contributors {.unnumbered}

This book is the result of the partnership between the APDVS and the Audible Bleeding Podcast, each of which are comprised of hard working individuals dedicated to medical education and the promotion of vascular surgery. They have freely donated their time to contribute to this work and we owe them a debt of gratitude. Follow them on twitter or other social media platforms to keep up to date with what they have going on.

**Angela Kokkosis, MD, FACS.** Associate Professor of Surgery; Program Director, Vascular and Endovascular Residency; Director, Carotid Interventions; Co-Medical Director, Non-Invasive Vascular Laboratory; *Stony Brook University* [Academic Profile](https://renaissance.stonybrookmedicine.edu/surgery/people/faculty/dr-angela-a-kokkosis) [\@Angela_Kokkosis](https://twitter.com/Angela_Kokkosis)

**Michael Malinowski, MD, MEHP, FACS.** Associate Professor; *Medical College of Wisconsin, Froedert Hospital* [Academic Profile](https://www.froedtert.com/doctors/michael-malinowski-1316100860)
