# Authors and Contributors {.unnumbered}

This eBook is the result of a partnership between the APDVS and the Audible Bleeding Podcast, each of which is comprised of hard working individuals dedicated to medical education and the promotion of vascular surgery. The authors and contributors of this eBook have freely donated their time and experience to create this resource. Please follow them on twitter or other social media platforms to return this debt of gratitude and to, as Audible Bleeding says, "keep a finger on the pulse."

**Ezra Schwartz, MDCM, MSc, MMSc.** *Harvard Medical School* [\@EzraSchwartz10](https://twitter.com/EzraSchwartz10)

**Yasong**

**Angela Kokkosis, MD, FACS.** Associate Professor of Surgery; Program Director, Vascular and Endovascular Residency; Director, Carotid Interventions; Co-Medical Director, Non-Invasive Vascular Laboratory; *Stony Brook University* [Academic Profile](https://renaissance.stonybrookmedicine.edu/surgery/people/faculty/dr-angela-a-kokkosis) [\@Angela_Kokkosis](https://twitter.com/Angela_Kokkosis)

**Michael Malinowski, MD, MEHP, FACS.** Associate Professor; *Medical College of Wisconsin, Froedert Hospital* [Academic Profile](https://www.froedtert.com/doctors/michael-malinowski-1316100860)
